#!/usr/bin/env python3
"""
This module contains functions for performing specific tasks.
"""

import duckdb

con = duckdb.connect("/home/keiza/.repo/public/my_dbt/dev.duckdb", read_only=True)
print(con.sql("select * from test limit 10"))
print(con.sql("select count(*) as total_rides from my_first_dbt_model"))

# if(con.execute('select count(*) as total_rides from taxi_rides_raw').fetchall()[0][0] == 300000):

#     with open('/home/repl/workspace/successful_data_check', 'w',encoding='utf-8') as f:
#         f.write('300000')
